DROP TABLE user_contact CASCADE ;
DROP TABLE test_entities CASCADE;
DROP TABLE message CASCADE ;
DROP TABLE file_download CASCADE ;
DROP TABLE fag CASCADE ;
DROP TABLE document CASCADE ;
DROP TABLE book_two_user_type CASCADE ;
DROP TABLE book_two_user CASCADE ;
DROP TABLE book_two_genre CASCADE ;
DROP TABLE book_two_author CASCADE ;
DROP TABLE book_review_like CASCADE ;
DROP TABLE book_review CASCADE ;
DROP TABLE book_file CASCADE ;
DROP TABLE book_file_type CASCADE ;
DROP TABLE biography CASCADE ;

DROP TABLE balance_transaction CASCADE ;
DROP TABLE authors CASCADE ;
DROP TABLE genre CASCADE ;
DROP TABLE customer CASCADE ;
DROP TABLE books CASCADE ;
